config/routes.rb
SWS::Application.routes.draw do
  scope 'api' do
    resources :youtube  
  end

  match "sessions/new", to: "sessions#new"
  match "sessions/destroy", to: "sessions#destroy"  

  # OMNIAUTH Routes
  # root to: "sessions#new"              
  match "/auth/:provider/callback", to: "sessions#create"
  match "/auth/failure", to: "sessions#failure"

  resources :identities
  resources :workouts

  resources :users do
    resources :workouts
  end
  resources :searches

  match "/workouts/add_stage/:stage_id", to: "workouts#add_stage"

# Backbone will handle the "stage/:num" portion of the url
  match "/workouts/:id/*all", to: "workouts#show"

  match "/stages/created/:id", to: "stages#created"

  resources :stages
  match "/stages/:id/*all", to: "stages#show"

  match "/workouts/created/:id", to: "workouts#created"

  resources :workouts do
    resources :stages
  end

  # /workouts/new => BackboneView

  # An explicit path for testing purposes
  match '/home', :to => "pages#home"

  resources :log

  # An implicit matching path for all else
  match '*path', :to => "pages#home"

  #match '/contact', :to => 'pages#contact'
  #match '/about', :to => 'pages#about'
  #match '/help', :to => 'pages#help'
  #
  #
  #
  root :to => 'pages#home'
  

  # OBSOLETE: WORKOUT SNIPPETS
  #match '/workouts/:id/snippet' => 'workouts#snippet'
  #match '/workouts/gallery/:page' => 'workouts#gallery'

  # WORKOUT DATA
  #match '/workout/:id' => "workouts#show"
  #match '/youtube/:id' => "youtube#show"

  #match '/workout/workout-1234.xml', :to => redirect('/public/workout/workout-1234.xml')
  #match '/workout/workout-2345.xml', :to => redirect('/public/workout/workout-2345.xml')
  ###

end

app/views/nav/_performance.html.erb
<nav id="bottom_nav" class="navbar navbar-default navbar-fixed-bottom" role="navigation" style="display:none;">
  <div id="bottom_graph" class="row" style="padding-bottom:5px;"></div>
</nav>

app/views/nav/_subsection.erb
<div><%= link_to "Workouts", workouts_path, 'data-pjax' => '#center-html' %>
	 <%= link_to "Workout Stages", stages_path, 'data-pjax' => '#center-html' %>
</div>

app/views/nav/_top.html.erb
<nav id="nav_top" class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-sws-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a id="brand-logo" class="navbar-brand pjax" style="padding-top:9px; padding-bottom:0px;" href="/"><img src="<%= asset_path 'spinworkouts-logobeta.png' %>"></a>
  </div>
  <div id="nav_dynamic" class="collapse navbar-collapse navbar-sws-collapse">
    <!-- Everything you want hidden at 940px or less, place within here -->
    <!--<div id="nav_msg"></div>-->
  </div>
</nav>

app/views/nav/_user.html.erb
<ul id="nav_user" class="nav pull-right">
<% if current_user %>
    <li>
      <%= link_to "My Workouts", user_workouts_path({:user_id => current_user.id}), :class => 'pjax' %>
    </li>
    <li>
      <%= link_to "Sign out", "/sessions/destroy", :id => 'signout' %>
    </li>
<% else %>
    <li>
        <%= link_to "Sign in", "/sessions/new", :id => 'signin' %>
    </li>
<% end %>
</ul>